### ISSUE TITLE
It only predict draw

### ISSUE THREAD

**Issue by GrindTiger** [binayachaudari/EPL-predict-2019#1]

**Comment by GrindTiger** [comment]
When i try with fixtures it predict draw in entire season

**Comment by binayachaudari** [comment]
If you could provide me the fixtures, I could try to fix the issue.

**Comment by GrindTiger** [comment]
I used your dataset the way it is

**Comment by binayachaudari** [comment]
Seems like something went wrong with logistic regression, may be it's because of the package upgrade..

Anyways, will try to fix it.

**Comment by GrindTiger** [comment]
Okay
